"""empty message

Revision ID: 083db9ffb2e8
Revises: dcf110663978
Create Date: 2020-07-11 22:27:45.589653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '083db9ffb2e8'
down_revision = 'dcf110663978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_survey_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_quota', sa.Integer(), nullable=False),
    sa.Column('remaining_quota', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_annotation_sentences',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('outlet', sa.String(length=100), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['test_survey_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_annotation_sentences')
    op.drop_table('test_survey_groups')
    # ### end Alembic commands ###
