"""empty message

Revision ID: 649015aba760
Revises: 083db9ffb2e8
Create Date: 2020-07-11 22:40:49.430506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649015aba760'
down_revision = '083db9ffb2e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_survey_annotations',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('survey_record_id', sa.String(length=150), nullable=True),
    sa.Column('annotation_sentence_id', sa.String(length=150), nullable=True),
    sa.Column('label', sa.Integer(), nullable=False),
    sa.Column('words', sa.Text(), nullable=False),
    sa.Column('factual', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_sentence_id'], ['test_annotation_sentences.id'], ),
    sa.ForeignKeyConstraint(['survey_record_id'], ['survey_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_survey_annotations')
    # ### end Alembic commands ###
