"""empty message

Revision ID: 72059829a787
Revises: 13a072bf43f7
Create Date: 2020-07-13 20:56:37.980930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72059829a787'
down_revision = '13a072bf43f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_pool', 'survey_record_id',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.drop_constraint('user_pool_ibfk_1', 'user_pool', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('user_pool_ibfk_1', 'user_pool', 'survey_record', ['survey_record_id'], ['id'])
    op.alter_column('user_pool', 'survey_record_id',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    # ### end Alembic commands ###
