"""empty message

Revision ID: cd4ec2a9fd7d
Revises: bc34e366c71c
Create Date: 2020-07-10 19:54:51.650647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd4ec2a9fd7d'
down_revision = 'bc34e366c71c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotation_sentences', 'dummy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_sentences', sa.Column('dummy', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
