"""empty message

Revision ID: dcf110663978
Revises: ec9724f485d5
Create Date: 2020-07-11 22:22:01.960996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf110663978'
down_revision = 'ec9724f485d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_quota', sa.Integer(), nullable=False),
    sa.Column('remaining_quota', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotation_sentences',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('outlet', sa.String(length=100), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['survey_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_annotations',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('survey_record_id', sa.String(length=150), nullable=True),
    sa.Column('annotation_sentence_id', sa.String(length=150), nullable=True),
    sa.Column('label', sa.Integer(), nullable=False),
    sa.Column('words', sa.Text(), nullable=False),
    sa.Column('factual', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_sentence_id'], ['annotation_sentences.id'], ),
    sa.ForeignKeyConstraint(['survey_record_id'], ['survey_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_annotations')
    op.drop_table('annotation_sentences')
    op.drop_table('survey_groups')
    # ### end Alembic commands ###
